apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: online-ide
  labels:
    app: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-sa
  namespace: online-ide
  labels:
    app: project
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-sa
  namespace: online-ide
  labels:
    app: ui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compiler-sa
  namespace: online-ide
  labels:
    app: compiler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dark-mode-sa
  namespace: online-ide
  labels:
    app: dark-mode
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: online-ide
  labels:
    app: oide-db
