apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 6.2.5
      helm:
        valueFiles:
          - $values/argocd/helm-values/falco-values.yaml
    - repoURL: https://gitlab.lrz.de/container-security-wizards/online-ide.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
