apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  sources:
    - repoURL: https://open-policy-agent.github.io/gatekeeper/charts
      chart: gatekeeper
      targetRevision: 3.20.1
      helm:
        valueFiles:
          - $values/argocd/helm-values/gatekeeper-values.yaml
    - repoURL: https://gitlab.lrz.de/container-security-wizards/online-ide.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true