apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: additional-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://gitlab.lrz.de/container-security-wizards/online-ide.git
    targetRevision: main
    path: argocd/secrets
    directory:
      include: "additional-secrets.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true