apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://gitlab.lrz.de/container-security-wizards/online-ide.git
    targetRevision: main
    path: argocd/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: online-ide
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
